# This is a reference file - actual branch protection is configured in GitHub repository settings
# Go to Settings -> Branches -> Add branch protection rule

rules:
  - pattern: "master"
    required_status_checks:
      strict: true
      contexts:
        - "build-and-test"
        - "security-scan"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_last_push_approval: true
    restrictions: null
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
    enforce_admins: false

  - pattern: "feature"
    required_status_checks:
      strict: false
      contexts:
        - "build-and-test"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false