# Configuration for auto-assigning reviewers
default:
  reviewers:
    - 'RadwanAyoub'
  team_reviewers:
    - 'REPLACE_WITH_DEFAULT_TEAM_SLUG'

file_patterns:
  # Backend (.NET) patterns
  - patterns:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
    reviewers:
      - 'RadwanAyoub'
    team_reviewers:
      - 'REPLACE_WITH_BACKEND_TEAM_SLUG'

  # Frontend patterns
  - patterns:
      - '**/*.tsx'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.jsx'
      - '**/package.json'
      - '**/src/frontend/**'
    reviewers:
      - 'RadwanAyoub'
    team_reviewers:
      - 'REPLACE_WITH_FRONTEND_TEAM_SLUG'

  # Infrastructure patterns
  - patterns:
      - '**/.github/workflows/*'
      - '**/Dockerfile*'
      - '**/docker-compose*.yml'
      - '**/*.yaml'
      - '**/*.yml'
    reviewers:
      - 'RadwanAyoub'
    team_reviewers:
      - 'REPLACE_WITH_INFRA_TEAM_SLUG'

  # Database patterns
  - patterns:
      - '**/Migrations/**'
      - '**/*DbContext*.cs'
      - '**/appsettings*.json'
    reviewers:
      - 'RadwanAyoub'